packages:

  # 将packages文件夹下的所有直接子文件夹添加到workspace
  # all packages in direct subdirs of packages/
  - 'packages/*'

  # all packages in subdirs of components/
  - 'components/**'

  # exclude packages that are inside test directories
  #- '!**/test/**'

  # workspace添加一个api模块——封装fetch用于网络请求
  - 'api/**'